[package]
name = "completion"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.12.23", features = ["json"] }
serde_json = "1.0.144"
tokio = { version = "1.47.1", features = ["full"] }
